name: BlazzOS
options:
  bundleIdPrefix: dev.blazz
  deploymentTarget:
    macOS: "14.0"
    iOS: "17.0"
  xcodeVersion: "16.0"
configFiles:
  Debug: Config/Debug.xcconfig
  Release: Config/Release.xcconfig
settings:
  base:
    DEVELOPMENT_TEAM: P9KAWJ28LA
    CODE_SIGN_STYLE: Automatic
    CODE_SIGN_IDENTITY: "Apple Development"
targets:
  BlazzOS:
    type: application
    platform: macOS
    sources:
      - BlazzOS
      - Shared
    dependencies:
      - target: BlazzOSWidget
    settings:
      base:
        INFOPLIST_FILE: BlazzOS/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: dev.blazz.blazzos
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_VERSION: "5.9"
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/../Frameworks"
        ENABLE_HARDENED_RUNTIME: false
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        CODE_SIGN_ENTITLEMENTS: BlazzOS/BlazzOS.entitlements
  BlazzOSWidget:
    type: app-extension
    platform: macOS
    sources:
      - path: BlazzOSWidget
        excludes:
          - Info.plist
          - BlazzOSWidget.entitlements
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: dev.blazz.blazzos.widget
        SWIFT_VERSION: "5.9"
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        INFOPLIST_FILE: BlazzOSWidget/Info.plist
        CODE_SIGN_ENTITLEMENTS: BlazzOSWidget/BlazzOSWidget.entitlements
    dependencies:
      - sdk: WidgetKit.framework
      - sdk: SwiftUI.framework
  BlazzOSIOS:
    type: application
    platform: iOS
    sources:
      - path: BlazzOSIOS
        excludes:
          - Info.plist
      - Shared
    settings:
      base:
        INFOPLIST_FILE: BlazzOSIOS/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: dev.blazz.blazzos.ios
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_VERSION: "5.9"
        IPHONEOS_DEPLOYMENT_TARGET: "17.0"
        TARGETED_DEVICE_FAMILY: "1,2"
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: "NO"
  BlazzOSTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - BlazzOSTests
    dependencies:
      - target: BlazzOS
    settings:
      base:
        SWIFT_VERSION: "5.9"
        GENERATE_INFOPLIST_FILE: "YES"
