// ── UI Primitives ──────────────────────────────
export * from "./components/ui/alert"
export * from "./components/ui/avatar"
export * from "./components/ui/badge"
export * from "./components/ui/banner"
export * from "./components/ui/bleed"
export * from "./components/ui/block-stack"
export * from "./components/ui/box"
export * from "./components/ui/breadcrumb"
export * from "./components/ui/button"
export * from "./components/ui/button-group"
export * from "./components/ui/calendar"
export * from "./components/ui/callout-card"
export * from "./components/ui/card"
export * from "./components/ui/carousel"
export * from "./components/ui/chart"
export * from "./components/ui/checkbox"
export * from "./components/ui/collapsible"
export * from "./components/ui/color-picker"
export * from "./components/ui/combobox"
export * from "./components/ui/command"
export * from "./components/ui/confirmation-dialog"
export * from "./components/ui/currency-input"
export * from "./components/ui/date-selector"
export * from "./components/ui/dialog"
export * from "./components/ui/divider"
export * from "./components/ui/dropdown-menu"
export * from "./components/ui/empty"
export * from "./components/ui/field"
export * from "./components/ui/file-upload"
export * from "./components/ui/filters"
export * from "./components/ui/frame-panel"
export * from "./components/ui/grid"
export * from "./components/ui/hover-card"
export * from "./components/ui/inline-grid"
export * from "./components/ui/inline-stack"
export * from "./components/ui/input"
export * from "./components/ui/input-group"
export * from "./components/ui/label"
export * from "./components/ui/menu"
export * from "./components/ui/menubar"
export * from "./components/ui/nav-menu"
export * from "./components/ui/number-input"
export * from "./components/ui/otp-input"
export * from "./components/ui/page"
export * from "./components/ui/pagination"
export * from "./components/ui/password-input"
export * from "./components/ui/phone-input"
export * from "./components/ui/popover"
export * from "./components/ui/progress"
export * from "./components/ui/property"
export * from "./components/ui/radio-group"
export * from "./components/ui/rating"
export * from "./components/ui/scroll-area"
export * from "./components/ui/search-input"
export * from "./components/ui/select"
export * from "./components/ui/separator"
export * from "./components/ui/sheet"
export * from "./components/ui/sidebar"
export * from "./components/ui/skeleton"
export * from "./components/ui/slider"
export * from "./components/ui/spinner"
export * from "./components/ui/stepper"
export * from "./components/ui/switch"
export * from "./components/ui/table"
export * from "./components/ui/tabs"
export * from "./components/ui/tags-input"
export * from "./components/ui/text"
export * from "./components/ui/textarea"
export * from "./components/ui/time-picker"
export * from "./components/ui/timeline"
export * from "./components/ui/tooltip"
export * from "./components/ui/tree-view"

// ── Block Components ───────────────────────────
export * from "./components/blocks/activity-timeline"
export * from "./components/blocks/bulk-action-bar"
export * from "./components/blocks/area-chart-block"
export * from "./components/blocks/bar-chart-block"
export * from "./components/blocks/chart-card"
export * from "./components/blocks/line-chart-block"
export * from "./components/blocks/pie-chart-block"
export * from "./components/blocks/radar-chart-block"
export * from "./components/blocks/data-grid"
export * from "./components/blocks/deal-lines-editor"
export * from "./components/blocks/detail-panel"
export * from "./components/blocks/error-state"
export { FieldGrid, type FieldGridProps } from "./components/blocks/field-grid"
export * from "./components/blocks/filter-bar"
export * from "./components/blocks/forecast-chart"
export * from "./components/blocks/form-field"
export * from "./components/blocks/form-section"
export * from "./components/blocks/funnel-chart"
export * from "./components/blocks/inline-edit"
export * from "./components/blocks/kanban-board"
export * from "./components/blocks/multi-step-form"
export * from "./components/blocks/notification-center"
export * from "./components/blocks/org-menu"
export * from "./components/blocks/page-header"
export * from "./components/blocks/property-card"
export * from "./components/blocks/quick-log-activity"
export * from "./components/blocks/quote-preview"
export * from "./components/blocks/split-view"
export * from "./components/blocks/stats-grid"
export * from "./components/blocks/stats-strip"
export * from "./components/blocks/status-flow"

// ── AI Components ──────────────────────────────
// Barrel has naming conflicts (DataGrid, Timeline, StatItem…)
// Import AI components from "@blazz/ui/components/ai"

// ── Features ───────────────────────────────────
// DataTable barrel has naming conflicts (BulkAction, RowAction, FilterGroup, FilterOperator)
// Import DataTable from "@blazz/ui/components/features/data-table"
export * from "./components/features/command-palette/command-palette"
export * from "./components/features/image-upload/image-upload"
export * from "./components/features/image-upload/image-preview"
export * from "./components/features/navigation-tabs"

// ── Layout ─────────────────────────────────────
export * from "./components/layout/app-frame"
export * from "./components/layout/app-sidebar"
export * from "./components/layout/app-top-bar"
export { type FrameProps } from "./components/layout/frame"
export { type Breadcrumb as FrameBreadcrumb, FrameProvider, useFrame, useBreadcrumbs } from "./components/layout/frame-context"
export * from "./components/layout/layout-frame"
export * from "./components/layout/layout-top-bar"
export * from "./components/layout/mobile-sidebar-sheet"
export * from "./components/layout/nav-tabs"
export * from "./components/layout/navbar"
export * from "./components/layout/dashboard-layout"
export * from "./components/layout/notification-sheet"
export { type BreadcrumbItemType } from "./components/layout/page-header"
export * from "./components/layout/sidebar-exports"
export * from "./components/layout/sidebar-search"
export * from "./components/layout/sidebar-user"
export * from "./components/layout/tab-bar"
export * from "./components/layout/theme-palette-switcher"
export * from "./components/layout/theme-toggle"
export * from "./components/layout/top-bar"
export * from "./components/layout/user-menu"

// ── Hooks ──────────────────────────────────────
export * from "./hooks/use-block-navigation"
export * from "./hooks/use-command-palette"
export * from "./hooks/use-data-table-url-state"
export * from "./hooks/use-data-table-views"
export * from "./hooks/use-debounced"
export * from "./hooks/use-navigation-with-params"

// ── Utilities ──────────────────────────────────
export { cn } from "./lib/utils"
export * from "./lib/utils/index"
export * from "./lib/theme-context"
export * from "./lib/use-frame-layout"
export * from "./lib/tab-utils"

// ── Types ──────────────────────────────────────
export * from "./types/navigation"
