import type { ComponentType } from "react"
// ── AI Components ────────────────────────────────────────────────────────────
import {
	AiActionListPreview,
	AiApprovalCardPreview,
	AiAvailabilityCardPreview,
	// Scheduling
	AiCalendarCardPreview,
	// CRM entities
	AiCandidateCardPreview,
	AiChainOfThoughtPreview,
	AiChecklistCardPreview,
	AiCompanyCardPreview,
	AiComparisonTablePreview,
	AiConfirmationPreview,
	AiContactCardPreview,
	// Chat
	AiConversationPreview,
	AiDataGridPreview,
	AiDataListPreview,
	AiDealCardPreview,
	// Communication
	AiEmailPreviewPreview,
	AiEventCardPreview,
	AiFileCardPreview,
	AiImageGalleryPreview,
	// Insights & analytics
	AiInsightCardPreview,
	// Financial
	AiInvoiceCardPreview,
	AiLinkPreviewPreview,
	// Location & media
	AiLocationCardPreview,
	AiMessagePreview,
	AiMessagePreviewPreview,
	// Metrics & data
	AiMetricCardPreview,
	AiMiniChartPreview,
	AiModelSelectorPreview,
	AiPollCardPreview,
	AiPricingTablePreview,
	AiProgressCardPreview,
	AiPromptInputPreview,
	AiQuoteSummaryPreview,
	AiRatingCardPreview,
	// Reasoning & sources
	AiReasoningPreview,
	AiScoreCardPreview,
	AiSourcesPreview,
	AiStatsRowPreview,
	AiStatusUpdatePreview,
	AiSuggestionPreview,
	AiSummaryCardPreview,
	// Tasks & workflow
	AiTaskCardPreview,
	// Activity & workflow
	AiTimelinePreview,
	AiTransactionCardPreview,
	AiUserCardPreview,
	AiVideoCardPreview,
} from "./ai-previews"

// ── Block Components ─────────────────────────────────────────────────────────
import {
	ActivityTimelinePreview,
	BulkActionBarPreview,
	ChartCardPreview,
	DetailPanelPreview,
	ErrorStatePreview,
	FieldGridPreview,
	FilterBarPreview,
	FormFieldPreview,
	FormSectionPreview,
	MultiStepFormPreview,
	PageHeaderPreview,
	SplitViewPreview,
	StatsGridPreview,
	StatusFlowPreview,
} from "./block-previews"
// ── UI Primitives ────────────────────────────────────────────────────────────
import {
	AlertPreview,
	AvatarPreview,
	BadgePreview,
	BannerPreview,
	BreadcrumbPreview,
	ButtonGroupPreview,
	ButtonPreview,
	CalendarPreview,
	CellsPreview,
	CheckboxPreview,
	CommandPreview,
	ConfirmationDialogPreview,
	DataTablePreview,
	DateSelectorPreview,
	DialogPreview,
	DropdownMenuPreview,
	EmptyPreview,
	FramePanelPreview,
	InputPreview,
	MenubarPreview,
	MenuPreview,
	NavMenuPreview,
	NotificationCenterPreview,
	OrgMenuPreview,
	PhoneInputPreview,
	PopoverPreview,
	PropertyCardPreview,
	PropertyPreview,
	SelectPreview,
	SheetPreview,
	SkeletonPreview,
	StatsStripPreview,
	SwitchPreview,
	TablePreview,
	TabsPreview,
	TextareaPreview,
	TextPreview,
	TooltipPreview,
} from "./ui-previews"

/**
 * Maps every thumbnail slug (from thumbnail-registry.ts) to its preview component.
 * Every slug in the registry MUST have a corresponding entry here.
 */
export const previewMap: Record<string, ComponentType> = {
	// ── UI Primitives (37) ───────────────────────────────────────────────────
	alert: AlertPreview,
	avatar: AvatarPreview,
	badge: BadgePreview,
	banner: BannerPreview,
	breadcrumb: BreadcrumbPreview,
	button: ButtonPreview,
	"button-group": ButtonGroupPreview,
	calendar: CalendarPreview,
	cells: CellsPreview,
	checkbox: CheckboxPreview,
	command: CommandPreview,
	"confirmation-dialog": ConfirmationDialogPreview,
	"data-table": DataTablePreview,
	"date-selector": DateSelectorPreview,
	dialog: DialogPreview,
	"dropdown-menu": DropdownMenuPreview,
	empty: EmptyPreview,
	"frame-panel": FramePanelPreview,
	input: InputPreview,
	menu: MenuPreview,
	menubar: MenubarPreview,
	"nav-menu": NavMenuPreview,
	"notification-center": NotificationCenterPreview,
	"org-menu": OrgMenuPreview,
	"phone-input": PhoneInputPreview,
	popover: PopoverPreview,
	property: PropertyPreview,
	"property-card": PropertyCardPreview,
	select: SelectPreview,
	sheet: SheetPreview,
	skeleton: SkeletonPreview,
	"stats-strip": StatsStripPreview,
	switch: SwitchPreview,
	table: TablePreview,
	tabs: TabsPreview,
	text: TextPreview,
	textarea: TextareaPreview,
	tooltip: TooltipPreview,

	// ── Block Components (15) ────────────────────────────────────────────────
	"activity-timeline": ActivityTimelinePreview,
	"bulk-action-bar": BulkActionBarPreview,
	"chart-card": ChartCardPreview,
	"detail-panel": DetailPanelPreview,
	"error-state": ErrorStatePreview,
	"field-grid": FieldGridPreview,
	"filter-bar": FilterBarPreview,
	"form-field": FormFieldPreview,
	"form-section": FormSectionPreview,
	"multi-step-form": MultiStepFormPreview,
	"page-header": PageHeaderPreview,
	"split-view": SplitViewPreview,
	"stats-grid": StatsGridPreview,
	"status-flow": StatusFlowPreview,

	// ── AI Components (46) ──────────────────────────────────────────────────
	// Chat
	"ai-conversation": AiConversationPreview,
	"ai-message": AiMessagePreview,
	"ai-prompt-input": AiPromptInputPreview,
	"ai-suggestion": AiSuggestionPreview,
	// Reasoning & sources
	"ai-reasoning": AiReasoningPreview,
	"ai-chain-of-thought": AiChainOfThoughtPreview,
	"ai-sources": AiSourcesPreview,
	"ai-confirmation": AiConfirmationPreview,
	"ai-model-selector": AiModelSelectorPreview,
	// Metrics & data
	"ai-metric-card": AiMetricCardPreview,
	"ai-stats-row": AiStatsRowPreview,
	"ai-mini-chart": AiMiniChartPreview,
	"ai-comparison-table": AiComparisonTablePreview,
	"ai-progress-card": AiProgressCardPreview,
	"ai-data-list": AiDataListPreview,
	"ai-data-grid": AiDataGridPreview,
	// CRM entities
	"ai-candidate-card": AiCandidateCardPreview,
	"ai-contact-card": AiContactCardPreview,
	"ai-company-card": AiCompanyCardPreview,
	"ai-deal-card": AiDealCardPreview,
	"ai-user-card": AiUserCardPreview,
	// Activity & workflow
	"ai-timeline": AiTimelinePreview,
	"ai-event-card": AiEventCardPreview,
	"ai-status-update": AiStatusUpdatePreview,
	"ai-approval-card": AiApprovalCardPreview,
	"ai-action-list": AiActionListPreview,
	"ai-poll-card": AiPollCardPreview,
	// Communication
	"ai-email-preview": AiEmailPreviewPreview,
	"ai-message-preview": AiMessagePreviewPreview,
	// Tasks & workflow
	"ai-task-card": AiTaskCardPreview,
	"ai-checklist-card": AiChecklistCardPreview,
	// Financial
	"ai-invoice-card": AiInvoiceCardPreview,
	"ai-quote-summary": AiQuoteSummaryPreview,
	"ai-pricing-table": AiPricingTablePreview,
	"ai-transaction-card": AiTransactionCardPreview,
	// Scheduling
	"ai-calendar-card": AiCalendarCardPreview,
	"ai-availability-card": AiAvailabilityCardPreview,
	// Insights & analytics
	"ai-insight-card": AiInsightCardPreview,
	"ai-summary-card": AiSummaryCardPreview,
	"ai-rating-card": AiRatingCardPreview,
	"ai-score-card": AiScoreCardPreview,
	// Location & media
	"ai-location-card": AiLocationCardPreview,
	"ai-video-card": AiVideoCardPreview,
	"ai-file-card": AiFileCardPreview,
	"ai-link-preview": AiLinkPreviewPreview,
	"ai-image-gallery": AiImageGalleryPreview,
}
