"use client";

import {
  Brain,
  Calendar,
  ChartLine,
  CreditCard,
  FileText,
  FormInput,
  Layers,
  LayoutGrid,
  ListChecks,
  MessageCircle,
  MousePointerClick,
  Navigation,
  Palette,
  Table2,
  MessageSquare,
  Users,
  Wrench,
} from "lucide-react";
import type { SidebarConfig } from "@/types/navigation";

export const sidebarConfig: SidebarConfig = {
  user: {
    name: "Jean Dupont",
    email: "",
    role: "Administrateur",
  },
  navigation: [
    {
      id: "foundations",
      title: "Foundations",
      items: [
        {
          id: "theming",
          title: "Theming",
          url: "/docs/theming",
          icon: Palette,
        },
      ],
    },
    {
      id: "components",
      title: "Components",
      items: [
        {
          id: "comp-layout",
          title: "Layout and Structure",
          url: "/docs/components/layout",
          icon: LayoutGrid,
          items: [
            { title: "Bleed", url: "/docs/components/layout/bleed" },
            { title: "Block Stack", url: "/docs/components/layout/block-stack" },
            { title: "Box", url: "/docs/components/layout/box" },
            { title: "Callout Card", url: "/docs/components/layout/callout-card" },
            { title: "Card", url: "/docs/components/layout/card" },
            { title: "Divider", url: "/docs/components/layout/divider" },
            { title: "Frame", url: "/docs/components/ui/frame-panel" },
            { title: "Grid", url: "/docs/components/layout/grid" },
            { title: "Inline Grid", url: "/docs/components/layout/inline-grid" },
            { title: "Inline Stack", url: "/docs/components/layout/inline-stack" },
            { title: "Page", url: "/docs/components/layout/page-component" },
          ],
        },
        {
          id: "comp-actions",
          title: "Actions",
          url: "/docs/components/actions",
          icon: MousePointerClick,
          items: [
            { title: "Button", url: "/docs/components/ui/button" },
            { title: "Button Group", url: "/docs/components/ui/button-group" },
            { title: "Dropdown Menu", url: "/docs/components/ui/dropdown-menu" },
          ],
        },
        {
          id: "comp-forms",
          title: "Selection and Input",
          url: "/docs/components/forms",
          icon: FormInput,
          items: [
            { title: "Calendar", url: "/docs/components/ui/calendar" },
            { title: "Checkbox", url: "/docs/components/ui/checkbox" },
            { title: "Date Selector", url: "/docs/components/ui/date-selector" },
            { title: "Input", url: "/docs/components/ui/input" },
            { title: "Phone Input", url: "/docs/components/ui/phone-input" },
            { title: "Select", url: "/docs/components/ui/select" },
            { title: "Switch", url: "/docs/components/ui/switch" },
            { title: "Textarea", url: "/docs/components/ui/textarea" },
          ],
        },
        {
          id: "comp-feedback",
          title: "Feedback Indicators",
          url: "/docs/components/feedback",
          icon: MessageSquare,
          items: [
            { title: "Alert", url: "/docs/components/ui/alert" },
            { title: "Badge", url: "/docs/components/ui/badge" },
            { title: "Banner", url: "/docs/components/ui/banner" },
            { title: "Empty", url: "/docs/components/ui/empty" },
            { title: "Notification Center", url: "/docs/components/ui/notification-center" },
            { title: "Skeleton", url: "/docs/components/ui/skeleton" },
          ],
        },
        {
          id: "comp-overlays",
          title: "Overlays",
          url: "/docs/components/overlays",
          icon: Layers,
          items: [
            { title: "Confirmation Dialog", url: "/docs/components/ui/confirmation-dialog" },
            { title: "Dialog", url: "/docs/components/ui/dialog" },
            { title: "Popover", url: "/docs/components/ui/popover" },
            { title: "Sheet", url: "/docs/components/ui/sheet" },
            { title: "Tooltip", url: "/docs/components/ui/tooltip" },
          ],
        },
        {
          id: "comp-navigation",
          title: "Navigation",
          url: "/docs/components/navigation",
          icon: Navigation,
          items: [
            { title: "Breadcrumb", url: "/docs/components/ui/breadcrumb" },
            { title: "Command", url: "/docs/components/ui/command" },
            { title: "Menu", url: "/docs/components/ui/menu" },
            { title: "Menubar", url: "/docs/components/ui/menubar" },
            { title: "Nav Menu", url: "/docs/components/ui/nav-menu" },
            { title: "Org Menu", url: "/docs/components/ui/org-menu" },
            { title: "Tabs", url: "/docs/components/ui/tabs" },
          ],
        },
        {
          id: "comp-data-display",
          title: "Data Display",
          url: "/docs/components/data-display",
          icon: Table2,
          items: [
            { title: "Avatar", url: "/docs/components/ui/avatar" },
            { title: "Cell Types", url: "/docs/components/ui/cells" },
            { title: "Data Table", url: "/docs/components/ui/data-table" },
            { title: "Property", url: "/docs/components/ui/property" },
            { title: "Property Card", url: "/docs/components/ui/property-card" },
            { title: "Stats Strip", url: "/docs/components/ui/stats-strip" },
            { title: "Table", url: "/docs/components/ui/table" },
          ],
        },
        {
          id: "comp-foundations",
          title: "Foundations",
          url: "/docs/components/colors",
          icon: Palette,
          items: [
            { title: "Colors", url: "/docs/components/colors" },
            { title: "Typography", url: "/docs/components/typography" },
            { title: "Text", url: "/docs/components/ui/text" },
          ],
        },
      ],
    },
    {
      id: "ai",
      title: "AI",
      items: [
        {
          id: "ai-chat",
          title: "Chat",
          url: "/docs/components/ai/chat/conversation",
          icon: MessageCircle,
          items: [
            { title: "Conversation", url: "/docs/components/ai/chat/conversation" },
            { title: "Message", url: "/docs/components/ai/chat/message" },
            { title: "Prompt Input", url: "/docs/components/ai/chat/prompt-input" },
            { title: "Suggestion", url: "/docs/components/ai/chat/suggestion" },
            { title: "Attachments", url: "/docs/components/ai/chat/attachments" },
            { title: "Shimmer", url: "/docs/components/ai/chat/shimmer" },
          ],
        },
        {
          id: "ai-reasoning",
          title: "Reasoning",
          url: "/docs/components/ai/reasoning",
          icon: Brain,
          items: [
            { title: "Reasoning", url: "/docs/components/ai/reasoning" },
            { title: "Chain of Thought", url: "/docs/components/ai/chain-of-thought" },
            { title: "Sources", url: "/docs/components/ai/sources" },
            { title: "Inline Citation", url: "/docs/components/ai/inline-citation" },
          ],
        },
        {
          id: "ai-tools",
          title: "Tools",
          url: "/docs/components/ai/confirmation",
          icon: Wrench,
          items: [
            { title: "Confirmation", url: "/docs/components/ai/confirmation" },
            { title: "Model Selector", url: "/docs/components/ai/model-selector" },
            { title: "Context", url: "/docs/components/ai/context" },
          ],
        },
        {
          id: "ai-data",
          title: "Data",
          url: "/docs/components/ai/data/metric-card",
          icon: ChartLine,
          items: [
            { title: "Metric Card", url: "/docs/components/ai/data/metric-card" },
            { title: "Stats Row", url: "/docs/components/ai/data/stats-row" },
            { title: "Mini Chart", url: "/docs/components/ai/data/mini-chart" },
            { title: "Comparison Table", url: "/docs/components/ai/data/comparison-table" },
            { title: "Progress Card", url: "/docs/components/ai/data/progress-card" },
            { title: "Data List", url: "/docs/components/ai/data/data-list" },
            { title: "Data Grid", url: "/docs/components/ai/data/data-grid" },
            { title: "Rating Card", url: "/docs/components/ai/data/rating-card" },
            { title: "Score Card", url: "/docs/components/ai/data/score-card" },
          ],
        },
        {
          id: "ai-entities",
          title: "Entities",
          url: "/docs/components/ai/entities/candidate-card",
          icon: Users,
          items: [
            { title: "Candidate Card", url: "/docs/components/ai/entities/candidate-card" },
            { title: "Contact Card", url: "/docs/components/ai/entities/contact-card" },
            { title: "Company Card", url: "/docs/components/ai/entities/company-card" },
            { title: "Deal Card", url: "/docs/components/ai/entities/deal-card" },
            { title: "User Card", url: "/docs/components/ai/entities/user-card" },
          ],
        },
        {
          id: "ai-workflow",
          title: "Workflow",
          url: "/docs/components/ai/workflow/task-card",
          icon: ListChecks,
          items: [
            { title: "Task Card", url: "/docs/components/ai/workflow/task-card" },
            { title: "Checklist Card", url: "/docs/components/ai/workflow/checklist-card" },
            { title: "Approval Card", url: "/docs/components/ai/workflow/approval-card" },
            { title: "Action List", url: "/docs/components/ai/workflow/action-list" },
            { title: "Poll Card", url: "/docs/components/ai/workflow/poll-card" },
            { title: "Email Preview", url: "/docs/components/ai/workflow/email-preview" },
            { title: "Message Preview", url: "/docs/components/ai/workflow/message-preview" },
          ],
        },
        {
          id: "ai-planning",
          title: "Planning",
          url: "/docs/components/ai/planning/timeline",
          icon: Calendar,
          items: [
            { title: "Timeline", url: "/docs/components/ai/planning/timeline" },
            { title: "Event Card", url: "/docs/components/ai/planning/event-card" },
            { title: "Status Update", url: "/docs/components/ai/planning/status-update" },
            { title: "Calendar Card", url: "/docs/components/ai/planning/calendar-card" },
            { title: "Availability Card", url: "/docs/components/ai/planning/availability-card" },
          ],
        },
        {
          id: "ai-commerce",
          title: "Commerce",
          url: "/docs/components/ai/commerce/invoice-card",
          icon: CreditCard,
          items: [
            { title: "Invoice Card", url: "/docs/components/ai/commerce/invoice-card" },
            { title: "Quote Summary", url: "/docs/components/ai/commerce/quote-summary" },
            { title: "Pricing Table", url: "/docs/components/ai/commerce/pricing-table" },
            { title: "Transaction Card", url: "/docs/components/ai/commerce/transaction-card" },
          ],
        },
        {
          id: "ai-content",
          title: "Content",
          url: "/docs/components/ai/content/insight-card",
          icon: FileText,
          items: [
            { title: "Insight Card", url: "/docs/components/ai/content/insight-card" },
            { title: "Summary Card", url: "/docs/components/ai/content/summary-card" },
            { title: "File Card", url: "/docs/components/ai/content/file-card" },
            { title: "Link Preview", url: "/docs/components/ai/content/link-preview" },
            { title: "Image Gallery", url: "/docs/components/ai/content/image-gallery" },
            { title: "Location Card", url: "/docs/components/ai/content/location-card" },
            { title: "Video Card", url: "/docs/components/ai/content/video-card" },
          ],
        },
      ],
    },
  ],
};

// Backward compatibility - export navigationConfig as before
export const navigationConfig = sidebarConfig.navigation;
