import type { Invitation, User } from "@/types/user-management"

/**
 * Mock users data
 */
export const mockUsers: User[] = [
	{
		id: "usr_1",
		email: "john.doe@example.com",
		name: "John Doe",
		firstName: "John",
		lastName: "Doe",
		username: "johndoe",
		role: "admin",
		status: "active",
		emailAddresses: [
			{
				id: "email_1",
				email: "john.doe@example.com",
				isPrimary: true,
				isVerified: true,
				createdAt: "2024-01-15T10:00:00Z",
			},
			{
				id: "email_2",
				email: "john.work@company.com",
				isPrimary: false,
				isVerified: true,
				createdAt: "2024-02-20T14:30:00Z",
			},
		],
		metadata: {
			public: { department: "Engineering", location: "Paris" },
			private: { phoneNumber: "+33612345678", emergencyContact: "Jane Doe" },
			unsafe: { internalId: "EMP-001", accessLevel: 5 },
		},
		permissions: {
			canDeleteAccount: true,
			bypassClientTrust: false,
		},
		lastSignedIn: "2024-12-20T09:15:00Z",
		createdAt: "2024-01-15T10:00:00Z",
		updatedAt: "2024-12-20T09:15:00Z",
		devices: [],
	},
	{
		id: "usr_2",
		email: "sarah.smith@example.com",
		name: "Sarah Smith",
		firstName: "Sarah",
		lastName: "Smith",
		username: "sarahsmith",
		role: "user",
		status: "active",
		emailAddresses: [
			{
				id: "email_3",
				email: "sarah.smith@example.com",
				isPrimary: true,
				isVerified: true,
				createdAt: "2024-02-01T08:00:00Z",
			},
		],
		metadata: {
			public: { department: "Marketing", location: "Lyon" },
			private: { phoneNumber: "+33698765432" },
			unsafe: { internalId: "EMP-002", accessLevel: 3 },
		},
		permissions: {
			canDeleteAccount: true,
			bypassClientTrust: false,
		},
		lastSignedIn: "2024-12-19T16:45:00Z",
		createdAt: "2024-02-01T08:00:00Z",
		updatedAt: "2024-12-19T16:45:00Z",
		devices: [],
	},
	{
		id: "usr_3",
		email: "mike.johnson@example.com",
		name: "Mike Johnson",
		firstName: "Mike",
		lastName: "Johnson",
		username: "mikej",
		role: "user",
		status: "inactive",
		emailAddresses: [
			{
				id: "email_4",
				email: "mike.johnson@example.com",
				isPrimary: true,
				isVerified: true,
				createdAt: "2024-03-10T11:20:00Z",
			},
		],
		metadata: {
			public: { department: "Sales", location: "Marseille" },
			private: { phoneNumber: "+33645678901" },
			unsafe: { internalId: "EMP-003", accessLevel: 2 },
		},
		permissions: {
			canDeleteAccount: false,
			bypassClientTrust: false,
		},
		lastSignedIn: "2024-10-15T14:30:00Z",
		createdAt: "2024-03-10T11:20:00Z",
		updatedAt: "2024-10-15T14:30:00Z",
		devices: [],
	},
	{
		id: "usr_4",
		email: "emma.wilson@example.com",
		name: "Emma Wilson",
		firstName: "Emma",
		lastName: "Wilson",
		username: "emmaw",
		role: "moderator",
		status: "active",
		emailAddresses: [
			{
				id: "email_5",
				email: "emma.wilson@example.com",
				isPrimary: true,
				isVerified: true,
				createdAt: "2024-04-05T09:00:00Z",
			},
		],
		metadata: {
			public: { department: "Customer Support", location: "Toulouse" },
			private: { phoneNumber: "+33656789012" },
			unsafe: { internalId: "EMP-004", accessLevel: 4 },
		},
		permissions: {
			canDeleteAccount: true,
			bypassClientTrust: true,
		},
		lastSignedIn: "2024-12-21T08:00:00Z",
		createdAt: "2024-04-05T09:00:00Z",
		updatedAt: "2024-12-21T08:00:00Z",
		devices: [],
	},
	{
		id: "usr_5",
		email: "david.brown@example.com",
		name: "David Brown",
		firstName: "David",
		lastName: "Brown",
		username: "davidb",
		role: "user",
		status: "suspended",
		emailAddresses: [
			{
				id: "email_6",
				email: "david.brown@example.com",
				isPrimary: true,
				isVerified: false,
				createdAt: "2024-05-12T13:45:00Z",
			},
		],
		metadata: {
			public: { department: "Operations", location: "Bordeaux" },
			private: {},
			unsafe: { internalId: "EMP-005", accessLevel: 1 },
		},
		permissions: {
			canDeleteAccount: false,
			bypassClientTrust: false,
		},
		lastSignedIn: "2024-11-01T10:20:00Z",
		createdAt: "2024-05-12T13:45:00Z",
		updatedAt: "2024-11-01T10:20:00Z",
		devices: [],
	},
	{
		id: "usr_6",
		email: "lisa.anderson@example.com",
		name: "Lisa Anderson",
		firstName: "Lisa",
		lastName: "Anderson",
		username: "lisaa",
		role: "user",
		status: "never_active",
		emailAddresses: [
			{
				id: "email_7",
				email: "lisa.anderson@example.com",
				isPrimary: true,
				isVerified: false,
				createdAt: "2024-12-01T10:00:00Z",
			},
		],
		metadata: {
			public: { department: "HR", location: "Nice" },
			private: {},
			unsafe: { internalId: "EMP-006", accessLevel: 2 },
		},
		permissions: {
			canDeleteAccount: true,
			bypassClientTrust: false,
		},
		lastSignedIn: undefined,
		createdAt: "2024-12-01T10:00:00Z",
		updatedAt: "2024-12-01T10:00:00Z",
		devices: [],
	},
	{
		id: "usr_7",
		email: "robert.taylor@example.com",
		name: "Robert Taylor",
		firstName: "Robert",
		lastName: "Taylor",
		username: "robertt",
		role: "admin",
		status: "active",
		emailAddresses: [
			{
				id: "email_8",
				email: "robert.taylor@example.com",
				isPrimary: true,
				isVerified: true,
				createdAt: "2024-01-20T12:00:00Z",
			},
		],
		metadata: {
			public: { department: "Engineering", location: "Paris" },
			private: { phoneNumber: "+33667890123" },
			unsafe: { internalId: "EMP-007", accessLevel: 5 },
		},
		permissions: {
			canDeleteAccount: true,
			bypassClientTrust: true,
		},
		lastSignedIn: "2024-12-21T11:30:00Z",
		createdAt: "2024-01-20T12:00:00Z",
		updatedAt: "2024-12-21T11:30:00Z",
		devices: [],
	},
	{
		id: "usr_8",
		email: "jennifer.white@example.com",
		name: "Jennifer White",
		firstName: "Jennifer",
		lastName: "White",
		username: "jenniferw",
		role: "user",
		status: "active",
		emailAddresses: [
			{
				id: "email_9",
				email: "jennifer.white@example.com",
				isPrimary: true,
				isVerified: true,
				createdAt: "2024-06-15T15:30:00Z",
			},
		],
		metadata: {
			public: { department: "Finance", location: "Lille" },
			private: { phoneNumber: "+33678901234" },
			unsafe: { internalId: "EMP-008", accessLevel: 3 },
		},
		permissions: {
			canDeleteAccount: true,
			bypassClientTrust: false,
		},
		lastSignedIn: "2024-12-20T13:00:00Z",
		createdAt: "2024-06-15T15:30:00Z",
		updatedAt: "2024-12-20T13:00:00Z",
		devices: [],
	},
	{
		id: "usr_9",
		email: "chris.martin@example.com",
		name: "Chris Martin",
		firstName: "Chris",
		lastName: "Martin",
		username: "chrism",
		role: "user",
		status: "inactive",
		emailAddresses: [
			{
				id: "email_10",
				email: "chris.martin@example.com",
				isPrimary: true,
				isVerified: true,
				createdAt: "2024-07-20T10:15:00Z",
			},
		],
		metadata: {
			public: { department: "Legal", location: "Nantes" },
			private: {},
			unsafe: { internalId: "EMP-009", accessLevel: 2 },
		},
		permissions: {
			canDeleteAccount: false,
			bypassClientTrust: false,
		},
		lastSignedIn: "2024-09-10T16:00:00Z",
		createdAt: "2024-07-20T10:15:00Z",
		updatedAt: "2024-09-10T16:00:00Z",
		devices: [],
	},
	{
		id: "usr_10",
		email: "amanda.garcia@example.com",
		name: "Amanda Garcia",
		firstName: "Amanda",
		lastName: "Garcia",
		username: "amandag",
		role: "moderator",
		status: "active",
		emailAddresses: [
			{
				id: "email_11",
				email: "amanda.garcia@example.com",
				isPrimary: true,
				isVerified: true,
				createdAt: "2024-08-05T09:45:00Z",
			},
		],
		metadata: {
			public: { department: "Product", location: "Strasbourg" },
			private: { phoneNumber: "+33689012345" },
			unsafe: { internalId: "EMP-010", accessLevel: 4 },
		},
		permissions: {
			canDeleteAccount: true,
			bypassClientTrust: false,
		},
		lastSignedIn: "2024-12-21T07:30:00Z",
		createdAt: "2024-08-05T09:45:00Z",
		updatedAt: "2024-12-21T07:30:00Z",
		devices: [],
	},
]

/**
 * Mock invitations data
 */
export const mockInvitations: Invitation[] = [
	{
		id: "inv_1",
		email: "new.user@example.com",
		role: "user",
		status: "pending",
		invitedAt: "2024-12-15T10:00:00Z",
		expiresAt: "2024-12-22T10:00:00Z",
		invitedBy: "John Doe",
	},
	{
		id: "inv_2",
		email: "jane.doe@example.com",
		role: "moderator",
		status: "accepted",
		invitedAt: "2024-12-10T14:30:00Z",
		expiresAt: "2024-12-17T14:30:00Z",
		invitedBy: "Robert Taylor",
	},
	{
		id: "inv_3",
		email: "expired.user@example.com",
		role: "user",
		status: "expired",
		invitedAt: "2024-11-20T09:00:00Z",
		expiresAt: "2024-11-27T09:00:00Z",
		invitedBy: "John Doe",
	},
	{
		id: "inv_4",
		email: "revoked.user@example.com",
		role: "user",
		status: "revoked",
		invitedAt: "2024-12-05T11:15:00Z",
		expiresAt: "2024-12-12T11:15:00Z",
		invitedBy: "Emma Wilson",
	},
	{
		id: "inv_5",
		email: "another.pending@example.com",
		role: "user",
		status: "pending",
		invitedAt: "2024-12-18T16:00:00Z",
		expiresAt: "2024-12-25T16:00:00Z",
		invitedBy: "Amanda Garcia",
	},
]
