/**
 * Sample data for Linear Issues DataTable preset
 * Mock data replicating a Linear-style issue tracker
 */

/* ─── Types ─── */

export type IssueStatus = "backlog" | "todo" | "in_progress" | "done" | "cancelled"
export type IssuePriority = "urgent" | "high" | "medium" | "low" | "none"

export interface LinearIssue {
	id: string
	identifier: string
	title: string
	status: IssueStatus
	priority: IssuePriority
	labels: string[]
	project?: string
	assigneeName?: string
	assigneeAvatar?: string
	createdAt: string
}

/* ─── Issues (20) ─── */

export const linearIssues: LinearIssue[] = [
	{
		id: "li1",
		identifier: "CEN-104",
		title: "Importer les données CSV depuis l'ancien système",
		status: "backlog",
		priority: "high",
		labels: ["backend", "migration"],
		project: "Module 2 - Articles/Clients",
		assigneeName: "Pierre Martin",
		assigneeAvatar: "",
		createdAt: "2026-02-03",
	},
	{
		id: "li2",
		identifier: "CEN-103",
		title: "Historiser les prix des articles",
		status: "backlog",
		priority: "medium",
		labels: ["backend", "Articles"],
		project: "Module 2 - Articles/Clients",
		assigneeName: "Sophie Durand",
		assigneeAvatar: "",
		createdAt: "2026-02-02",
	},
	{
		id: "li3",
		identifier: "CEN-102",
		title: "Gérer les paramètres de facturation",
		status: "backlog",
		priority: "low",
		labels: ["frontend", "Facturation"],
		project: "Module 3 - Facturation",
		createdAt: "2026-02-01",
	},
	{
		id: "li4",
		identifier: "CEN-101",
		title: "Ajouter la recherche full-text sur les contacts",
		status: "backlog",
		priority: "medium",
		labels: ["backend", "Clients"],
		project: "Module 2 - Articles/Clients",
		assigneeName: "Pierre Martin",
		assigneeAvatar: "",
		createdAt: "2026-01-30",
	},
	{
		id: "li5",
		identifier: "CEN-100",
		title: "Corriger l'affichage du tableau de bord mobile",
		status: "backlog",
		priority: "high",
		labels: ["frontend", "bug"],
		project: "Module 1 - Dashboard",
		assigneeName: "Julie Lambert",
		assigneeAvatar: "",
		createdAt: "2026-01-28",
	},
	{
		id: "li6",
		identifier: "CEN-99",
		title: "Implémenter le système de notifications email",
		status: "backlog",
		priority: "medium",
		labels: ["backend", "notifications"],
		project: "Module 4 - Notifications",
		createdAt: "2026-01-27",
	},
	{
		id: "li7",
		identifier: "CEN-98",
		title: "Créer le composant de sélection de dates",
		status: "todo",
		priority: "medium",
		labels: ["frontend", "composants"],
		project: "Module 1 - Dashboard",
		assigneeName: "Julie Lambert",
		assigneeAvatar: "",
		createdAt: "2026-01-25",
	},
	{
		id: "li8",
		identifier: "CEN-97",
		title: "Optimiser les requêtes SQL du rapport mensuel",
		status: "todo",
		priority: "high",
		labels: ["backend", "performance"],
		project: "Module 5 - Rapports",
		assigneeName: "Marc Lefevre",
		assigneeAvatar: "",
		createdAt: "2026-01-24",
	},
	{
		id: "li9",
		identifier: "CEN-96",
		title: "Ajouter l'export PDF des devis",
		status: "todo",
		priority: "urgent",
		labels: ["backend", "Facturation"],
		project: "Module 3 - Facturation",
		assigneeName: "Sophie Durand",
		assigneeAvatar: "",
		createdAt: "2026-01-22",
	},
	{
		id: "li10",
		identifier: "CEN-95",
		title: "Valider les champs du formulaire de création client",
		status: "todo",
		priority: "low",
		labels: ["frontend", "Clients"],
		project: "Module 2 - Articles/Clients",
		createdAt: "2026-01-20",
	},
	{
		id: "li11",
		identifier: "CEN-94",
		title: "Intégrer l'API de paiement Stripe",
		status: "in_progress",
		priority: "urgent",
		labels: ["backend", "paiement"],
		project: "Module 3 - Facturation",
		assigneeName: "Pierre Martin",
		assigneeAvatar: "",
		createdAt: "2026-01-18",
	},
	{
		id: "li12",
		identifier: "CEN-93",
		title: "Refactorer le module d'authentification",
		status: "in_progress",
		priority: "high",
		labels: ["backend", "sécurité"],
		project: "Module 1 - Dashboard",
		assigneeName: "Marc Lefevre",
		assigneeAvatar: "",
		createdAt: "2026-01-15",
	},
	{
		id: "li13",
		identifier: "CEN-92",
		title: "Implémenter le drag & drop sur le kanban",
		status: "in_progress",
		priority: "medium",
		labels: ["frontend", "composants"],
		project: "Module 1 - Dashboard",
		assigneeName: "Julie Lambert",
		assigneeAvatar: "",
		createdAt: "2026-01-12",
	},
	{
		id: "li14",
		identifier: "CEN-91",
		title: "Mettre en place les tests E2E Playwright",
		status: "in_progress",
		priority: "high",
		labels: ["testing", "infra"],
		assigneeName: "Sophie Durand",
		assigneeAvatar: "",
		createdAt: "2026-01-10",
	},
	{
		id: "li15",
		identifier: "CEN-90",
		title: "Configurer le pipeline CI/CD GitHub Actions",
		status: "done",
		priority: "high",
		labels: ["infra", "devops"],
		assigneeName: "Marc Lefevre",
		assigneeAvatar: "",
		createdAt: "2026-01-08",
	},
	{
		id: "li16",
		identifier: "CEN-89",
		title: "Créer la page de connexion SSO",
		status: "done",
		priority: "medium",
		labels: ["frontend", "sécurité"],
		project: "Module 1 - Dashboard",
		assigneeName: "Julie Lambert",
		assigneeAvatar: "",
		createdAt: "2026-01-05",
	},
	{
		id: "li17",
		identifier: "CEN-88",
		title: "Déployer l'environnement de staging",
		status: "done",
		priority: "urgent",
		labels: ["infra", "devops"],
		assigneeName: "Pierre Martin",
		assigneeAvatar: "",
		createdAt: "2026-01-03",
	},
	{
		id: "li18",
		identifier: "CEN-87",
		title: "Rédiger la documentation API Swagger",
		status: "done",
		priority: "low",
		labels: ["documentation"],
		project: "Module 5 - Rapports",
		assigneeName: "Sophie Durand",
		assigneeAvatar: "",
		createdAt: "2025-12-28",
	},
	{
		id: "li19",
		identifier: "CEN-86",
		title: "Annuler la migration vers GraphQL",
		status: "cancelled",
		priority: "medium",
		labels: ["backend", "migration"],
		assigneeName: "Marc Lefevre",
		assigneeAvatar: "",
		createdAt: "2025-12-20",
	},
	{
		id: "li20",
		identifier: "CEN-85",
		title: "Supprimer l'ancien module de reporting",
		status: "cancelled",
		priority: "low",
		labels: ["backend", "cleanup"],
		project: "Module 5 - Rapports",
		createdAt: "2025-12-15",
	},
]
